### ISSUE TITLE
Update vendor dockershim

### ISSUE THREAD

**Issue by resouer** [kubernetes/frakti#138]
To fix the nil pointer here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/security_context.go#L129

cc @Crazykev Watch out for `staging` part

**Comment by Crazykev** [comment]
Sorry, I updated in my local branch, while my docker environment broke, and haven't got time to fix it yet. Will check this when come back to Hangzhou.

  
  
    Welcome!  
    
    
    
  

     
       
           
            
                            张浩

                浙江大学  VLIS/SEL实验室

                crazykev@zju.edu.cn
              
           
           
                 
           
       
   
  
 
On 05/09/2017 20:25, Harry Zhang wrote: To fix the nil pointer here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/security_context.go#L129
cc @Crazykev Watch out for staging part

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kubernetes/frakti","title":"kubernetes/frakti","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kubernetes/frakti"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Update vendor dockershim (#138)"}],"action":{"name":"View Issue","url":"https://github.com/kubernetes/frakti/issues/138"}}}

**Comment by feiskyer** [comment]
Fixed by #142.
