### ISSUE TITLE
Kubectl get nodes - Issue

### ISSUE THREAD

**Issue by harshapic** [kubernetes/frakti#173]
https://github.com/kubernetes/frakti/blob/master/docs/deploy.md

followed above steps to deploy frakti,hyperd, kubernetes on vmware-fusion (ubuntu-xenial), with 1master and 2 worker node setup.
workers got successfully registered to master but when i do "kubectl get nodes", its only displays master node.

Same setup if i do only with docker runtime it shows all nodes if i do "kubectl get nodes" (for this i followed this setup:  https://blog.microideation.com/2017/03/06/setting-up-kubernetes-cluster-for-container-orchestration/ ).

I am not getting what i am doing wrong in frakti deployment steps

**Comment by harshapic** [comment]
kubeadm init --pod-network-cidr 10.244.0.0/16 --kubernetes-version v1.7.0-alpha.4

instead of kubernetes version latest which is 1.8(alpha) or 1.6.6(stable) its not working.
It worked with v1.7.0-alpha.4 kubernetes version

**Comment by feiskyer** [comment]
@harshapic Thanks for reporting the problem. Tried both latest and stable kubernetes version:

- stable version (v1.6.6) works properly according to the guide
- latest version (v1.8-alpha) couldn't join node because of certificate not approving automatically (refer [here](https://github.com/kubernetes/kubeadm/issues/291#issuecomment-307374330)).

However, the certificate could be approved manually by running `kubectl certificate approve <csr-name>` (`<csr-name>` could be found by `kubectl get csr`) command on the master node.

**Comment by harshapic** [comment]
Thanks it helped...Now it is showing fine.... My another issue was previous my worker node's hostname all were same as master it is another issue. Now i changed my hostname for all machines. Now its perfect. Exactly followed steps in deployment doc and everything worked fine
