### ISSUE TITLE
Use Docker + runV + Kubernetes?

### ISSUE THREAD

**Issue by youzibaby** [kubernetes/frakti#269]
emm...I have a question，why k8s can't direct post a pod json to docker with runv, I mean use frakti to reserve requests post to hyperd is goodway？      [runv](https://feisky.xyz/container/runv.html)

**Comment by resouer** [comment]
@youzibaby It only make sense when mixed runtimes is plug into Kubernetes. i.e. runv and runc handle workloads on same node. Otherwise you will not be able to run host ns containers.

In this case:

1. Docker has no idea of which workload should be handled by runv, only CRI shim has this knowledge (from CRI PodSandbox spec).
2. frakti is the CRI shim.
3. In the coming future, it will become frakti + KataContainers, no hyperd.
