### ISSUE TITLE
[GSoC] Some questions about "containerd-kata"

### ISSUE THREAD

**Issue by ZeroMagic** [kubernetes/frakti#320]
Now, I am writing the proposal of "containerd-kata". There are some questions.

1. I want to know if we need to add image management in the project "containerd-kata".  @laijs

2. I think that in the project "containerd-kata", what I need to do is transfer the variables in annotations.go(https://github.com/containerd/cri/blob/master/pkg/annotations/annotations.go) to containerd so that containerd can distinguish kata sandbox from other container runtimes. Do I understand correctly? And what else do I need to do in respect of CRI. @Random-Liu

**Comment by resouer** [comment]
Yes of course image management should be implemented, otherwise how can you start container?

But you can leave the image audit features as NICE TO HAVE.

Using annotation is a possible way, but I would also encourage your brainstorm it. The policy is: do not change code in containerd/cri-containerd as possible.

**Comment by ZeroMagic** [comment]
What is the image audit features ? I google it. Nothing is helpful for me. And I have asked others. No one can answer me clearly.

**Comment by resouer** [comment]
```
    // ImageFSInfo returns information of the filesystem that is used to store images.
    rpc ImageFsInfo(ImageFsInfoRequest) returns (ImageFsInfoResponse) {}
```

**Comment by ZeroMagic** [comment]
@resouer Got it. Thx.
