### ISSUE TITLE
Deprecate dockershim in vendor and change to use new containerd based architecture

### ISSUE THREAD

**Issue by resouer** [kubernetes/frakti#323]
As the title said.

The code change will happen in this branch: https://github.com/kubernetes/frakti/tree/containerd-kata

And eventually be spitted to merge part to containerd org and others frakti master branch.

**Comment by t3hmrman** [comment]
Just wanted to note that Frakti v2 looks really exciting to me -- one of my biggest wants was to use frakti as it exists now with cri-containerd (which is what I run now). It looks like frakti v2 will "upgrade" (IMO, some may not consider docker -> containerd an upgrade possibly) both the runV side and the docker side.

Actually came in to make a ticket requesting clarification on how to use containerd instead of docker but looks like I won't need to :)

**Comment by resouer** [comment]
@t3hmrman Exactly, we are actively working on containerd + Kata with folks from Google and Hyper. There will be no docker & dockershim needed in the frakti v2 project.

**Comment by resouer** [comment]
The containerd plugin has been temporarily implemented on this dev branch:  https://github.com/hyperhq/kata-runtime/tree/shimv2

**Comment by t3hmrman** [comment]
Hey @resouer to make sure I clearly understand, which of these are right:

- Frakti v2 will be a containerd plugin
- Frakti v2 will be rolled into the kata-containers

Those two facts seem at odds, because `containerd` already has an untrusted workload runtime option (on which you could set `kata-runtime` to run your untrusted workloads) -- Also, it doesn't really make sense for Frakti to merge into `kata-runtime` because Frakti is supposed to be able to handle both untrusted and trusted runtimes.

Is there somewhere I could read a bit more about how the project is moving? I'm helicoptering by and not watching closely but if there's some mailing list or forum I could read I'll go do that.

**Comment by resouer** [comment]
Hi @t3hmrman, not sure if you have read the RuntimeClass proposal? See: https://github.com/kubernetes/community/blob/master/keps/sig-node/0014-runtime-class.md 

It's exactly where we are going. The trusted/untrusted annotations will be deprecated, and frakti v2 will only include several containerd focus plugins to handle runtimes, networking, and storage. And of course, a doc about how to set these pieces up to serve as a production ready runtime for Kubernetes.

**Comment by t3hmrman** [comment]
hey @resouer Thanks so much for the pointer, I haven't actually seen the RuntimeClass proposal at all. 

That makes total sense, frakti becoming a well-integrated containerd plugin sounds great -- I'm a huge fan of containerd (+ cri-containerd, the intergration was pretty smooth for them).

Thanks for taking the time to explain!
