### ISSUE TITLE
frakti permissions cleanup

### ISSUE THREAD

**Issue by cblecker** [kubernetes/frakti#348]
Hey frakti team!

I'd like to help clean up some of the github permissions to this repo.

Right now there are the following teams with permissions to this repo:
- @kubernetes/frakti-admins - admin access
- @kubernetes/frakti-maintainers - write access

And in addition, there are the following collaborators with direct permission:
- @bergwolf - write
- @Crazykev - read
- @heartlock - read
- @ZeroMagic - write

I'd like to propose the following changes:
- If @bergwolf and @ZeroMagic are still active with the project, they can be added to @kubernetes/frakti-maintainers to maintain write access, but they should go through the [community membership process](https://git.k8s.io/community/community-membership.md#member) first, to be added to the @kubernetes github org.
- If @Crazykev and @heartlock are still active with the project, and they need the ability to be assigned issues, they should go through the [community membership process](https://git.k8s.io/community/community-membership.md#member) to be added to the @kubernetes github org, which will automatically give them the read access they currently have.
- After the above is done, the direct permissions can be pulled back.

How does this sound? Please let me know 😄.

cc: @kubernetes/owners

**Comment by feiskyer** [comment]
@gnawux @bergwolf I'm not active for the project recently and I'd like to remove myself from the maintainers' list. Would some of you replace me in the kubernetes/frakti-maintainers and kubernetes/frakti-admins team?

**Comment by resouer** [comment]
Thanks! @feiskyer I believe @bergwolf 's contribution would be strong reference as new frakti maintainer.

I believe @Crazykev @heartlock will still be able to assign issues, I would like to mentor them go through membership ladder (and @bergwolf as well).

@cblecker Please kindly give me some time to fix the legacy issues here. Any deadline from your side?

**Comment by cblecker** [comment]
No specific deadline, no. As long as it’s in progress, I’m happy.

If there is anything I can do to help, please let me know.

**Comment by gnawux** [comment]
Thanks @feiskyer. 

Agree with @resouer, I think @bergwolf, who is in Berlin this week and not online at this time, will continue this work.

**Comment by cblecker** [comment]
/remove-lifecycle stale

@resouer @bergwolf Any update on this?

**Comment by cblecker** [comment]
/remove-lifecycle stale

@resouer @bergwolf Any update on this?

**Comment by mrbobbytables** [comment]
@resouer @feiskyer 
Checking back in regarding outside collaborators. At this point it's been over a year since the original issue was created 😬 We're now actively planning to clean up outside collaborators org wide on December 1st.

@ZeroMagic has been active ideally should apply for membership (along with being added to [frakti-maintainers](https://github.com/kubernetes/org/blob/d59dda41f8e9adb10a8a2386449121137845b88f/config/kubernetes/org.yaml#L1356-L1360)).

 @Crazykev, @heartlock, @bergwolf - have not been active in the past year (>5 Devstats recorded contributions in the last year) and I would suggest removal over applying for org membership.  -- As a note, even if removed, it **does not stop** people from contributing. It just means they'd have less permissions (would need `/ok-to-test` on PRs etc).

**Comment by mrbobbytables** [comment]
Permissions have been cleaned up. @Crazykev, @heartlock, @bergwolf if you need permissions to continue to work on fraki, Please go ahead and file for [org membership](https://github.com/kubernetes/community/blob/master/community-membership.md#member) and we can pursue adding you the appropriate groups for repo permissions 👍 

If you have any questions, please don't hesitate to reopen or ping me on slack.

Thanks!
/close
