### ISSUE TITLE
hybrid mode

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/frakti#75]
I really like the idea of being able to schedule pods into lightweight vm's. There are times though when having access to the underlying node is needed. So its rather awkward to only have one at a time. It would be awesome if the docker backend and hyper backend could co'exist on the host at the same time, and pick one or the other based on pod annotation. You could then even possibly use kubernetes itself, with a daemonset that's docker based, to enable and manage hyper support on a kubernetes cluster. Looking at hyper a bit, it looks like it could containerize nicely.

**Comment by resouer** [comment]
@kfox1111 We are generally happy to have this. According to discussions in original issue, https://github.com/kubernetes/kubernetes/issues/29913, kubelet does not have plan to support multi-runtimes in short term plan, and sig-node also agreed multi-runtimes will be better implemented by remote runtime itself. frakti is a nice place to do this.

**Comment by resouer** [comment]
In stead of adding a proxy in front, like: https://github.com/Mirantis/virtlet/blob/master/pkg/criproxy/proxy.go, we plant to vendor dockershim in order to reuse duplicated modules like networking.  cc @Crazykev

**Comment by ivan4th** [comment]
As of single-command demo, we envision it as a simple shell script that can be downloaded to a Linux or a Mac with Docker and used to launch kubeadm-dind-cluster (newer version will not need k8s source) and then install Virtlet on it (on Macs it'll be plain `qemu` instead of `qemu-kvm` but that doesn't matter much for demo purpose). Similar approach can be used for other projects that employ CRI proxy.

**Comment by resouer** [comment]
Thanks @ivan4th, after talk with other frakti maintainers, we reached an agreement that we should not hack container/sandbox ID. So we kept the vendor way. Although less elegant, but comfortable to CRI ...
